name: chatbots
version: '0.1.0.0'
author: Josh Cough
maintainer: joshcough@gmail.com
homepage:  https://github.com/joshcough/chatbots
license: MIT
license-file: LICENSE
category: Web
copyright: © 2019 Josh Cough
github: https://github.com/joshcough/chatbots
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wimplicit-prelude

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - DeriveTraversable
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - UndecidableInstances

dependencies:
  - base
  - protolude
  - string-conversions

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-pretty
    - aeson-typescript
    - amazonka
    - bcrypt
    - bytestring
    - containers
    - directory
    - esqueleto
    - exceptions
    - fast-logger
    - filepath
    - foldl
    - http-api-data
    - http-types
    - irc-core
    - jose
    - lens
    - lens-aeson
    - monad-control
    - monad-logger
    - mtl
    - nano-http >=0.1.1
    - network
    - persistent
    - persistent-postgresql
    - persistent-template
    - postgresql-simple-url
    - postgresql-simple
    - purescript-bridge >= 0.13
    - random
    - resource-pool
    - rollbar
    - safe
    - servant >= 0.13 && <= 0.14.1
    - servant-auth >=0.3.1.0
    - servant-auth-server
    - servant-errors >= 0.1.3.1
    - servant-server >= 0.13 && <= 0.14.1
    - servant-websockets
    - stm
    - template-haskell
    - text
    - time
    - transformers
    - transformers-base
    - trifecta
    - turtle
    - unliftio-core
    - unordered-containers
#    - uuid
    - vector
    - wai
    - wai-app-static
    - wai-cors
    - warp
    - websockets

executables:
  chatbots-server:
    main: Main.hs
    source-dirs: app/server
    dependencies:
      - chatbots

  formatter:
    main: Main.hs
    source-dirs: app/formatter
    dependencies:
      - chatbots

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - chatbots
      - hspec
      - persistent
      - postgres-options
      - text
      - tmp-postgres
      # moo postgres stuff
      - dbmigrations >= 2
      - HDBC-postgresql == 2.3.2.7
    ghc-options:
      - -Wall
      - -Werror
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Wimplicit-prelude
      - -threaded
